### ISSUE TITLE
Initial code review

### ISSUE THREAD

**Issue by tompaana** [tompaana/lazy-storage-replicator#1]
Code review for the first version of the project.

**Comment by lawrencegripper** [comment]
It's easy to read, nicely laid out and works great. Was able to get the tests up and running and play around.  

Only 3 bits have come up that I'd maybe suggest tweaking. 

I've added a "Both" to the storagetype enum as I thought it might make it easier for users who aren't familiar with bitwise stuff, what do you think? Struggled to come up with a better name for it as not keen on “Both”.

When listing files the continuation token stuff is something I'm not sure about. With the individual providers, I can call list and then, if the list is too long and results are paged, I'll get a continuation token to get the next set of paged results. With the mutli-storage-client I can't do that and was wondering if it should handle the underlying continuation stuff for the user or expose it out... but as there could be two continuation tokens, one from each service, it all gets a bit odd. So, I think I’m in favour of the multi-storage-client using the underlying continuation tokens, if they're returned from AWS/Azure, to pull down all the pages for the user. What do you think?

For speed, I think it makes sense to call both of the providers in parallel, where appropriate. I’ve had a go at this on a branch, tried to do some basic perf testing and showed a slight improvement but the file size in the test is pretty small. Using a larger file size didn’t result in an improvement as both Azure and AWS are capable of maxing out my 20mbps upload so parallel didn’t alter times significantly. Deploying a VM in Azure with more bandwidth did show an improvement, results below (dropped about 7sec on 15mb file). 

> Before:
> multi-storage-client-test.js
> multiStorageClient - uploadAndCheckFileExistsAndDeleteBothStorages
> 
> OK: 2 assertions (3015ms)
> 
> multi-storage-client-test.js
> multiStorageClient - uploadAndCheckFileExistsAndDeleteBothStorages
> 
> OK: 2 assertions (3062ms)
> 
> After:
> 
> 
> multi-storage-client-test.js
> multiStorageClient - uploadAndCheckFileExistsAndDeleteBothStorages
> 
> OK: 2 assertions (2390ms)
> 
> 
> multi-storage-client-test.js
> multiStorageClient - uploadAndCheckFileExistsAndDeleteBothStorages
> 
> OK: 2 assertions (2375ms)

<strike>https://github.com/tompaana/lazy-storage-replicator/blob/master/src/multi-storage-client.ts#L100</strike>
https://github.com/tompaana/lazy-storage-replicator/blob/65ecc9f85f139d5208b1084ed26611b3d297bda1/src/multi-storage-client.ts#L100

Lastly, little one: I’m not sure on the use case but, in the method above, would it make sense to have an indication of a partially succeeded operation to the caller? You might mistakenly interpret the empty list as meaning there are no files in that storage, rather than it being in an error state temporarily 

Hope this is useful! Great work on the project :)

**Comment by lawrencegripper** [comment]
Added PR #2 with parallel stuff

**Comment by tompaana** [comment]
1) Adding "Both" is a good idea and the best part is that the bitwise operations will still work as before.
2) Added issue #3 for paged file lists problem.
3) Parallelism FTW - good thinking!
4) For now I made the error message printed in console more informative (c2b4f39).
